### ISSUE TITLE
Conflicting requirements for google-cloud 0.32

### ISSUE THREAD

**Issue by aktech** [pydata/pandas-gbq#178] opened 2018-05-11 11:17 UTC
Here are the two conflicting requirements:

`pandas-gbq` doesn't works with google-cloud 0.32

```
pandas-gbq 0.4.1 has requirement google-cloud-bigquery>=0.29.0, but you'll have google-cloud-bigquery 0.28.0 which is incompatible.
```

```
google-cloud 0.32.0 has requirement google-cloud-bigquery<0.29dev,>=0.28.0, but you'll have google-cloud-bigquery 0.30.0 which is incompatible.
```

**Comment by maxim-lian** [comment] 2018-05-11 14:10
Thanks for the report @aktech 

Closing as an upstream issue and dupe of https://github.com/pydata/pandas-gbq/issues/165

**Closed by maxim-lian** 2018-05-11 14:10 UTC
