### ISSUE TITLE
Authenticate with credentials

### ISSUE THREAD

**Issue by rxuniverse** [pydata/pandas-gbq#156] opened 2018-04-05 19:16 UTC
Provide an option to authenticate with credentials instead of private keys.

Example use case: On Google Cloud compute engine, I can [obtain credentials](https://cloud.google.com/docs/authentication/production#obtaining_credentials_on_compute_engine_kubernetes_engine_app_engine_flexible_environment_and_cloud_functions) in a compute engine instance based on the service account assigned to compute engine, but I can not directly get the private key. 

If I pass credentials in the private key field, it fails as expected.
`>>> from google.auth import compute_engine`
`>>> credentials = compute_engine.Credentials()`
`>>> import pandas`
`>>> pandas.io.gbq.read_gbq(sql, project, private_key=credentials)`
`/env/local/lib/python2.7/site-packages/pandas_gbq/gbq.py:798: FutureWarning: verbose is deprecated and will be removed in a future version. Set logging level in order to vary verbosity
  "verbosity", FutureWarning, stacklevel=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/env/local/lib/python2.7/site-packages/pandas/io/gbq.py", line 99, in read_gbq
    **kwargs)
  File "/env/local/lib/python2.7/site-packages/pandas_gbq/gbq.py", line 810, in read_gbq
    dialect=dialect, auth_local_webserver=auth_local_webserver)
  File "/env/local/lib/python2.7/site-packages/pandas_gbq/gbq.py", line 180, in __init__
    self.credentials = self.get_credentials()
  File "/env/local/lib/python2.7/site-packages/pandas_gbq/gbq.py", line 189, in get_credentials
    return self.get_service_account_credentials()
  File "/env/local/lib/python2.7/site-packages/pandas_gbq/gbq.py", line 409, in get_service_account_credentials
    "Private key is missing or invalid. It should be service "
pandas_gbq.gbq.InvalidPrivateKeyFormat: Private key is missing or invalid. It should be service account private key JSON (file path or string contents) with at least two keys: 'client_email' and 'private_key'. Can be obtained from: https://console.developers.google.com/permissions/serviceaccounts`

**Comment by maxim-lian** [comment] 2018-04-05 19:49
Can you confirm that it doesn't work if you pass in no details? Application Default Credentials (which are supplied in GCE) should work by default.

**Comment by rxuniverse** [comment] 2018-04-05 21:48
To clarify, I am running this in a pod in Kubernetes Engine. I don't think there is an Application Default Credentials there. 

I am not sure if there is an Application Default Credentials for compute engine... 

I did try to run query without the private key field (from a shell in a pod in Kubernetes Engine), it asks for authorization
`>>> pandas.io.gbq.read_gbq(sql, project)`
`Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=495642085510-k0tmvj2m941jhre2nbqka17vqpjfddtd.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fbigquery&state=I9HkEQv3ywVTfJYfH1q1bIrlQLDrVl&prompt=consent&access_type=offline
Enter the authorization code: `

**Comment by maxim-lian** [comment] 2018-04-05 22:09
I'm fairly confident that there are ADCs on GKE. What are you seeing in the docs that makes you think there isn't?

> If your application runs on Compute Engine, Kubernetes Engine, the App Engine flexible environment, or Cloud Functions, you don't need to create your own service account. Compute Engine includes a default service account that is automatically created for you

What do you see if you run `import google; google.auth.default()`?

**Comment by tswast** [comment] 2018-04-07 00:30
Last I tried there was [some setup required to get application default credentials to work on Kubernetes Engine](https://cloud.google.com/kubernetes-engine/docs/tutorials/authenticating-to-cloud-platform).

**Comment by tswast** [comment] 2018-04-07 00:44
I agree that a way to provide general credentials is desired and have created a design proposal at https://github.com/pydata/pandas-gbq/issues/161. Closing this issue as a duplicate of that proposal.

**Closed by tswast** 2018-04-07 00:44 UTC

**Comment by rxuniverse** [comment] 2018-04-07 00:51
#161 looks very comprehensive! Feel free to ping me to discuss or verify CLs.
