### ISSUE TITLE
pandas requires google-cloud-python for Google BigQuery support:

### ISSUE THREAD

**Issue by netskink** [pydata/pandas-gbq#203] opened 2018-08-28 20:14 UTC
I used to do this in a datalab notebook

`df = gbq.read_gbq('SELECT * FROM gsd_sample.blackman75', PROJECT)`

Now, it says 
`ImportError: pandas requires google-cloud-python for Google BigQuery support: cannot import name make_exception
`

In the python notebook, I am doing:

```
import math
import shutil
import numpy as np
import pandas as pd
import tensorflow as tf
import re
import matplotlib.pyplot as plt
import IPython.display as ipd
import os
import io
import sys
import base64
import hashlib
from sklearn import preprocessing
import datetime
from pandas.io import gbq


import apache_beam as beam
print tf.__version__
```

And prior to that, I do this in the datalab notebook

`!pip install librosa soundfile google-cloud-storage pandas-gbq google-cloud-bigquery pandas-gbq google-cloud -U`

**Comment by tswast** [comment] 2018-08-28 21:32
Duplicate of 
https://github.com/pydata/pandas-gbq/issues/199

I don’t think there’s anything we can do to fix this in Datalab from this package.

**Closed by tswast** 2018-08-28 21:32 UTC

**Comment by tswast** [comment] 2018-08-28 21:34
Don’t install the plain google-cloud package. It’s deprecated.

**Comment by netskink** [comment] 2018-08-29 13:33
Removed google-cloud from pip.   Changed python interpreter from version 3 to version 2 and now it works.

**Comment by klekhraj** [comment] 2018-09-26 08:43
Hi,
I have tried removing google-cloud from pip, still its not working.
Though it is working for python 3 but I need this in python 2.

**Comment by max-sixty** [comment] 2018-09-26 15:15
@klekhraj what the error you're getting? What you get from `pip list` (or `!pip list` run from python)?

**Comment by klekhraj** [comment] 2018-09-27 13:01
Hi @max-sixty,
Here is a snapshot of the error I am getting.
![capture](https://user-images.githubusercontent.com/16509228/46147560-6709cd00-c283-11e8-8e17-fda0e87eac93.PNG)

**Comment by klekhraj** [comment] 2018-09-27 13:03
And the result I am getting from "!pip list"
Package                                         Version    
----------------------------------------------- -----------
absl-py                                         0.4.0      
alembic                                         0.8.10     
apache-airflow                                  1.9.0      
appdirs                                         1.4.3      
asn1crypto                                      0.24.0     
astor                                           0.7.1      
attrs                                           18.1.0     
Automat                                         0.7.0      
avro                                            1.8.2      
backports-abc                                   0.5        
backports.functools-lru-cache                   1.5        
backports.shutil-get-terminal-size              1.0.0      
backports.ssl-match-hostname                    3.5.0.1    
backports.weakref                               1.0.post1  
beautifulsoup4                                  4.6.3      
bleach                                          2.1.2      
blinker                                         1.4        
bokeh                                           0.13.0     
brewer2mpl                                      1.4.1      
bs4                                             0.0.1      
cachetools                                      2.1.0      
certifi                                         2018.8.13  
cffi                                            1.11.5     
chardet                                         3.0.4      
click                                           6.7        
cloudpickle                                     0.5.3      
configparser                                    3.5.0      
constantly                                      15.1.0     
crcmod                                          1.7        
croniter                                        0.3.25     
cryptography                                    2.3        
cryptography-vectors                            2.3        
cycler                                          0.10.0     
cytoolz                                         0.9.0.1    
dask                                            0.17.1     
datalab                                         1.1.3      
decorator                                       4.3.0      
dill                                            0.2.6      
distributed                                     1.21.8     
docutils                                        0.14       
entrypoints                                     0.2.3      
enum34                                          1.1.6      
fastcache                                       1.0.2      
Flask                                           0.11.1     
Flask-Admin                                     1.4.1      
Flask-Cache                                     0.13.1     
Flask-Login                                     0.2.11     
flask-swagger                                   0.2.13     
Flask-WTF                                       0.14       
funcsigs                                        1.0.0      
functools32                                     3.2.3.post2
future                                          0.16.0     
futures                                         3.2.0      
gast                                            0.2.0      
ggplot                                          0.6.8      
gitdb2                                          2.0.4      
GitPython                                       2.1.11     
google-api-core                                 0.1.4      
google-api-python-client                        1.6.2      
google-apitools                                 0.5.10     
google-auth                                     1.5.1      
google-auth-httplib2                            0.0.3      
google-auth-oauthlib                            0.1.0      
google-cloud-bigquery                           0.23.0     
google-cloud-core                               0.28.1     
google-cloud-dataflow                           2.0.0      
google-cloud-monitoring                         0.28.0     
google-resumable-media                          0.3.1      
googleapis-common-protos                        1.5.3      
googledatastore                                 7.0.1      
grpcio                                          1.14.1     
gunicorn                                        19.9.0     
h5py                                            2.7.1      
heapdict                                        1.0.0      
html5lib                                        1.0.1      
httplib2                                        0.11.3     
hyperlink                                       18.0.0     
idna                                            2.6        
imageio                                         2.3.0      
incremental                                     17.5.0     
ipaddress                                       1.0.22     
ipykernel                                       4.8.2      
ipython                                         5.8.0      
ipython-genutils                                0.2.0      
ipywidgets                                      7.2.1      
itsdangerous                                    0.24       
Jinja2                                          2.8        
jsonschema                                      2.6.0      
jupyter-client                                  5.2.3      
jupyter-core                                    4.4.0      
lime                                            0.1.1.23   
locket                                          0.2.0      
lockfile                                        0.12.2     
lxml                                            3.8.0      
Mako                                            1.0.7      
Markdown                                        2.6.11     
MarkupSafe                                      1.0        
matplotlib                                      2.1.2      
mistune                                         0.8.3      
mltoolbox-datalab-classification-and-regression 1.0.1      
mltoolbox-datalab-image-classification          0.2        
mock                                            2.0.0      
msgpack                                         0.5.6      
nbconvert                                       5.3.1      
nbformat                                        4.4.0      
networkx                                        2.1        
nltk                                            3.2.1      
notebook                                        5.6.0      
numpy                                           1.14.0     
oauth2client                                    2.2.0      
oauthlib                                        2.1.0      
olefile                                         0.45.1     
ordereddict                                     1.1        
packaging                                       17.1       
pandas                                          0.22.0     
pandas-gbq                                      0.3.0      
pandas-profiling                                1.4.1      
pandocfilters                                   1.4.2      
partd                                           0.3.8      
pathlib2                                        2.3.2      
patsy                                           0.5.0      
pbr                                             4.2.0      
pexpect                                         4.6.0      
pickleshare                                     0.7.4      
Pillow                                          3.4.1      
pip                                             18.0       
plotly                                          1.12.5     
prometheus-client                               0.3.1      
prompt-toolkit                                  1.0.15     
proto-google-cloud-datastore-v1                 0.90.0     
protobuf                                        3.5.2      
psutil                                          4.3.0      
ptyprocess                                      0.6.0      
pyasn1                                          0.4.4      
pyasn1-modules                                  0.2.2      
pycparser                                       2.18       
Pygments                                        2.1.3      
PyJWT                                           1.6.4      
pyOpenSSL                                       18.0.0     
pyparsing                                       2.2.0      
PySocks                                         1.6.8      
python-daemon                                   2.1.2      
python-dateutil                                 2.5.0      
python-editor                                   1.0.3      
python-nvd3                                     0.14.2     
python-slugify                                  1.1.4      
python-snappy                                   0.5.1      
pytz                                            2016.7     
PyWavelets                                      0.5.2      
PyYAML                                          3.13       
pyzmq                                           17.1.0     
requests                                        2.18.4     
requests-oauthlib                               0.8.0      
rsa                                             3.4.2      
scandir                                         1.9.0      
scikit-image                                    0.13.0     
scikit-learn                                    0.19.1     
scipy                                           1.0.0      
seaborn                                         0.7.0      
Send2Trash                                      1.5.0      
service-identity                                17.0.0     
setproctitle                                    1.1.10     
setuptools                                      40.0.0     
simplegeneric                                   0.8.1      
simplejson                                      3.16.0     
singledispatch                                  3.4.0.3    
six                                             1.10.0     
smmap2                                          2.0.4      
sortedcontainers                                2.0.4      
SQLAlchemy                                      1.2.10     
statsmodels                                     0.8.0      
subprocess32                                    3.5.2      
sympy                                           0.7.6.1    
tabulate                                        0.7.7      
tblib                                           1.3.2      
tensorboard                                     1.8.0      
tensorflow                                      1.8.0      
termcolor                                       1.1.0      
terminado                                       0.8.1      
testpath                                        0.3.1      
thrift                                          0.11.0     
toolz                                           0.9.0      
tornado                                         4.5.1      
traitlets                                       4.3.2      
Twisted                                         18.7.0     
Unidecode                                       1.0.22     
uritemplate                                     3.0.0      
urllib3                                         1.22       
wcwidth                                         0.1.7      
webencodings                                    0.5.1      
Werkzeug                                        0.14.1     
wheel                                           0.31.1     
widgetsnbextension                              3.2.1      
WTForms                                         2.2.1      
xgboost                                         0.6a2      
zict                                            0.1.3      
zope.deprecation                                4.3.0      
zope.interface                                  4.5.0

**Comment by klekhraj** [comment] 2018-09-27 13:04
And the result I am getting from "!pip list" on datalab.
[Pip list.txt](https://github.com/pydata/pandas-gbq/files/2424167/Pip.list.txt)

**Comment by max-sixty** [comment] 2018-09-27 13:33
@klekhraj you're running a very old version of `google-cloud-bigquery` - upgrade that and it should work!

**Comment by klekhraj** [comment] 2018-09-27 14:04
@max-sixty I have upgraded `google-cloud-bigquery`, still getting same error.

**Comment by klekhraj** [comment] 2018-09-27 14:05
@max-sixty, I have upgraded `google-cloud-bigquery`, now error has been changed to `ImportError: cannot import name _SCALAR_VALUE_TO_JSON_ROW`

**Comment by max-sixty** [comment] 2018-09-27 14:12
Ah: upgrade `pandas_gbq`

**Comment by klekhraj** [comment] 2018-10-01 12:47
Hey @max-sixty, upgrading `pandas_gbq` worked for the first time but when I reconnected cloud datalab same error (ImportError: `import name _SCALAR_VALUE_TO_JSON_ROW`) appeared while importing `google.cloud.datalab`
pip list -> 
[Pip list.txt](https://github.com/pydata/pandas-gbq/files/2433955/Pip.list.txt)

**Comment by max-sixty** [comment] 2018-10-01 15:40
Great!

**Comment by klekhraj** [comment] 2018-10-04 10:05
Thanks @max-sixty,
It worked.
👍
