### ISSUE TITLE
Implicit user authenication yields error, expliciet authentication works

### ISSUE THREAD

**Issue by dkapitan** [pydata/pandas-gbq#250] opened 2019-02-14 10:07 UTC
Seen on:
- Linux Debian
- Python 3.5
- pandas 0.23
- pandas-gbq 0.9
- pydata-google-auth 0.1

Implicit user authentication yields `bad request: invalid grant error`:

```
import pandas as pd
df = pd.read_gbq('select 1'', dialect='standard', project_id='some-project')
```

Expliciet user authentication and assigning it to `context.credentials` works:

```
import pydata_google_auth
import pandas as pd
import pandas_gbq

# explicitly authenticate user via URL and assign to pandas_gbq context
credentials = pydata_google_auth.get_user_credentials(
    ['https://www.googleapis.com/auth/cloud-platform'],
)
pandas_gbq.context.credentials = credentials

# now you can use pd.read_gbq
df = pd.read_gbq('select 1'', dialect='standard', project_id='some-project')
```

I first thought the error was due to different versions, but that doesn't seem the case. I have seen similar errors on different environments (OSX, python 3.7) and sometimes implicit works and sometimes it doesn't.

For now I can continu using `pandas-gbq` but would it be good to figure out what's causing this?

**Comment by tswast** [comment] 2019-02-15 01:10
Thanks for the report. I think this is a duplicate of https://github.com/pydata/pandas-gbq/issues/50

There are [several possible causes for this error](https://blog.timekit.io/google-oauth-invalid-grant-nightmare-and-how-to-fix-it-9f4efaf1da35). I believe the `google-auth` library automatically attempts to refresh tokens just before they expire, but there's probably more we can do to be more robust.

**Closed by tswast** 2019-02-15 01:10 UTC

**Comment by tswast** [comment] 2019-02-15 01:12
As stated in #50, you can try removing your credentials cache with `reauth=True`. Since pandas-gbq stores it's credentials cache in a different folder than directly using pydata-google-auth, that is a possible cause of this error.

**Comment by dkapitan** [comment] 2019-02-15 05:58
Thanks for the feedback @tswast. Regarding `reauth=True`: I have tried that as well, but it didn't solve the issue. So it seems it's something else than the cache.

```
import pandas as pd
pd.read_gbq('select 1', project_id='mq-kngf', dialect='standard', reauth=True)

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pandas_gbq/gbq.py", line 426, in run_query
    location=self.location,
  File "/usr/local/lib/python3.5/dist-packages/google/cloud/bigquery/client.py", line 1438, in query
    query_job._begin(retry=retry)
  File "/usr/local/lib/python3.5/dist-packages/google/cloud/bigquery/job.py", line 553, in _begin
    retry, method="POST", path=path, data=self.to_api_repr()
  File "/usr/local/lib/python3.5/dist-packages/google/cloud/bigquery/client.py", line 381, in _call_api
    return call()
  File "/usr/local/lib/python3.5/dist-packages/google/api_core/retry.py", line 270, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.5/dist-packages/google/api_core/retry.py", line 179, in retry_target
    return target()
  File "/usr/local/lib/python3.5/dist-packages/google/cloud/_http.py", line 319, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://www.googleapis.com/bigquery/v2/projects/mq-kngf/jobs: Invalid credential

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/gbq.py", line 108, in read_gbq
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pandas_gbq/gbq.py", line 836, in read_gbq
    schema, rows = connector.run_query(query, configuration=configuration)
  File "/usr/local/lib/python3.5/dist-packages/pandas_gbq/gbq.py", line 440, in run_query
    self.process_http_error(ex)
  File "/usr/local/lib/python3.5/dist-packages/pandas_gbq/gbq.py", line 391, in process_http_error
    raise GenericGBQException("Reason: {0}".format(ex))
pandas_gbq.gbq.GenericGBQException: Reason: 400 POST https://www.googleapis.com/bigquery/v2/projects/mq-kngf/jobs: Invalid credential
```
