### ISSUE TITLE
internalError from to_gbq when service account doesn't have 'can edit' rights to BQ dataset

### ISSUE THREAD

**Issue by ghost** [pydata/pandas-gbq#17] opened 2017-03-01 10:57 UTC
Command:

`to_gbq(df, destination_table='dataset_table',project_id='foo',verbose=False,if_exists='replace',private_key='path/to/key')`

Output:

`GenericGBQException: Reason: internalError, Message: An internal error occurred and the request could not be completed.`

I guess there is some other error metadata included in the API response but it's not printed with the exception message.

How to replicate?
- try to call to_gbq to a table with a service account which doesn't have rights to destination table's dataset

When I added the rights for a dataset, DF got smoothly written into a table.

**Comment by mremes** [comment] 2017-03-01 10:57
I can dig into this (can assign to me)

**Comment by jreback** [comment] 2017-03-01 20:02
@mremes assigned!

**Comment by tswast** [comment] 2018-04-07 00:46
@mremes What's the action to take here? Catch the error and report a better message?

**Comment by max-sixty** [comment] 2018-08-21 17:48
This now works as intended; e.g. 

```
GenericGBQException: Reason: 403 Access Denied: Dataset bigquery-public-data:austin_crime: The user [-] does not have bigquery.tables.create permission for dataset bigquery-public-data:austin_crime.
```

**Closed by max-sixty** 2018-08-21 17:48 UTC
Labels: error reporting
