### ISSUE TITLE
JSON error python 3

### ISSUE THREAD

**Issue by caiolopes** [pydata/pandas-gbq#115] opened 2018-02-05 17:15 UTC
I upgraded my script that uses pandas-gbq from python 2.7 to python 3.6 and it started to give me an error when trying to load the dataframe:

```
Errors:
--
file-00000000: Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 329; errors: 1. (error code: invalid)
file-00000000: Error while reading data, error message: JSON parsing error in row starting at position 30858: Parser terminated before end of string (error code: invalid)
```

Using the [python client for bigquery](https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/bigquery) directly I found out that the problem was related to `load_table_from_file` function.

It turns out that these lines (586, 587) in the gbq.py file was not right for the file_obj parameter, as stated at the API Reference here (https://googlecloudplatform.github.io/google-cloud-python/latest/bigquery/reference.html)

- file_obj (file) – A file handle opened in binary mode for reading.

```python
body = body.encode('utf-8')
body = BytesIO(body)

try:
    self.client.load_table_from_file(
        body,
        destination_table,
        job_config=job_config).result()
except self.http_error as ex:
    self.process_http_error(ex)
```

So I changed it to look like this:

```python
fd = tempfile.NamedTemporaryFile(mode="w", delete=False)
fd.write('{}\n'.format('\n'.join(rows)))
fd.close()

with open(fd.name, 'rb') as body:
    try:
        self.client.load_table_from_file(
            body,
            destination_table,
            job_config=job_config).result()
    except self.http_error as ex:
        self.process_http_error(ex)

os.remove(fd.name)
```

In this way it works.

I know it has something to do with special characters like ç and ãéó, etc, but I don't know another way to solve this.

**Comment by tswast** [comment] 2018-02-05 18:38
Thanks for the report @caiolopes. You are correct that the problem is with non-ASCII characters. This issue was also reported in https://github.com/pydata/pandas-gbq/issues/106, so I'm closing this as a duplicate of that bug.

I believe https://github.com/pydata/pandas-gbq/pull/108 fixes the issue, but we need to make a release with that fix in it. Thanks for your patience.

**Closed by tswast** 2018-02-05 18:38 UTC

**Comment by caiolopes** [comment] 2018-02-05 20:03
Thank you @tswast and sorry for not seeing the issue #106 beforehand.

The #108 indeed fixes my problem. I tried it by cloning the repo and using it and it works just fine.
