### ISSUE TITLE
Define path of bigquery_credentials.dat by environment var

### ISSUE THREAD

**Issue by jonathansp** [pydata/pandas-gbq#86] opened 2017-09-12 17:48 UTC
In a shared environment, the use of [hard-coded bigquery_credentials.dat](https://github.com/pydata/pandas-gbq/blob/master/pandas_gbq/gbq.py#L282) file name could be a problem. We should be able to define this path by using an environment variable, for instance, `PANDAS_GBQ_CREDENTIALS_FILE`.

**Comment by MaximilianR** [comment] 2017-09-12 18:07
Can we default to `GOOGLE_APPLICATION_CREDENTIALS`, or does this need to be additional? https://developers.google.com/identity/protocols/application-default-credentials

**Comment by parthea** [comment] 2017-09-12 18:08
Thanks for reporting this. I think this is a duplicate of #41. We have an improvement ready (#83) and I'm hoping to merge it tonight if there are no objections. Could you add comments to #83?

**Comment by andrelu** [comment] 2017-09-12 18:33
IMO it would be interesting to have a configurable path. In #83 we cannot set a default directory to store our config, this is interesting when having datascience isolate notebooks environments, you ll always store in ~/.config/pandas_gbq... Beside that, you always have to pass the credentials when executing read_gbq.

**Comment by andrelu** [comment] 2017-09-12 18:36
@MaximilianR I think that GOOGLE_APPLICATION_CREDENTIALS env is used for a different kind of credential.

**Comment by jonathansp** [comment] 2017-09-12 18:42
@parthea @MaximilianR could you please consider both approaches? Maybe it'll be tough asking our users for send `credentials_path` parameter every time they need to exec a query.

@MaximilianR, as @andrelu pointed out, `GOOGLE_APPLICATION_CREDENTIALS` seems to have another meaning.

**Comment by parthea** [comment] 2017-09-12 19:02
@jonathansp You're right. Users may not like sending `credentials_path` parameter every time they need to exec a query. I'll modify #83 tonight to use an environment variable, as you've done in #86, and remove `credentials_path` altogether. I'll start by building on top of your changes in #86 so we can keep that PR open to maintain authorship.

**Comment by MaximilianR** [comment] 2017-09-12 19:39
> I think that GOOGLE_APPLICATION_CREDENTIALS env is used for a different kind of credential.

Yes, you're right

**Comment by parthea** [comment] 2017-09-19 11:43
Closed via https://github.com/pydata/pandas-gbq/commit/dbfb4e92d4b26fe5cff6c22e9ae420b324b8ac5a

**Closed by parthea** 2017-09-19 11:43 UTC
