### ISSUE TITLE
Scope should be configurable

### ISSUE THREAD

**Issue by cneerdaels** [pydata/pandas-gbq#84] opened 2017-08-24 20:02 UTC
I've been joining a table in BQ, to a federated one (looks like a BQ table, but its actually a Google Sheet). It throws the error: “Encountered an error while globbing file pattern” 

I've found I needed to change:
scope = 'https://www.googleapis.com/auth/bigquery'     <in class GbqConnector>
  to:
scope = ['https://www.googleapis.com/auth/bigquery', 'https://www.googleapis.com/auth/drive']

though I suppose with other federated sources, the scope may need to be configurable.

**Comment by tswast** [comment] 2017-09-11 20:26
Thanks for the report!

Closing this as a duplicate of https://github.com/pydata/pandas-gbq/issues/38

**Closed by tswast** 2017-09-11 20:26 UTC
