### ISSUE TITLE
ENH: Clear authentication defaults with more fine-grained control

### ISSUE THREAD

**Issue by maxim-lian** [pydata/pandas-gbq#129] opened 2018-02-20 03:25 UTC
We have about 220 lines of code which handles authentication - do we need that? Generally the answer to "do we need something we do a lot of" is 'Yes', but asking regardless

My prior is that  we could:
1. Check if creds are passed by the user
2. Otherwise pass nothing through to the Google libraries, and let them manage the defaults

That would reduced the code we needed to maintain and conform to standards - Google have very reasonable defaults, and we make it harder for those to flow through - e.g. `PANDAS_GBQ_CREDENTIALS_FILE` is non-standard, every other implementation uses `GOOGLE_APPLICATION_CREDENTIALS`, so users need to have an additional setting to use this library

**Comment by tswast** [comment] 2018-02-21 13:10
I definitely think there is room for improvement here. My ideal flow would be:

1. Try to load cached user-auth credentials.
1. Use credentials as explicitly passed by the user.
    * Passing in the bytes of the JSON file as currently done for backwards compatibility.
    * Passing in a Credentials object from `google-auth`.
1. Try to create default credentials using `google-auth`.
1. Do three-legged OAuth to get user credentials.

Note that `google-auth` default credentials does not do three-legged OAuth, so I think that's an area where `pandas-gbq` will need to keep some auth code around.

**Comment by maxim-lian** [comment] 2018-02-21 18:56
And if we just didn't pass any creds along - we literally did nothing there - what would happen then? How much would the `google.cloud.bigquery`-like libraries do?

**Comment by tswast** [comment] 2018-02-21 19:23
The google-cloud-bigquery library just does #3

**Comment by maxim-lian** [comment] 2018-02-21 20:08
OK, thanks. I'll ponder

**Comment by caiolopes** [comment] 2018-02-26 14:12
Just a small suggestion on this subject, I really enjoy how this library handles the authentication:

https://github.com/nithinmurali/pygsheets

It gives me more freedom than pandas-gbq because it let me right now which gives me problems when running at appengine right now.

It let the user pass a custom credentials object and decide where to save the oauth store instead of `~./config/pandas-gbq/bigquery_credentials.dat`

**Comment by caiolopes** [comment] 2018-02-26 17:02
For example, the method `get_application_default_credentials` gets my project's default service account at appengine first instead of the json file at `PANDAS_GBQ_CREDENTIALS_FILE`.

And the worst part is that it doesn't allow me to modify this with any parameter in the `read_gbq`, `to_gbq`.

**Comment by tswast** [comment] 2018-02-27 00:56
@caiolopes Yes, that's good feedback. I actually forgot about `PANDAS_GBQ_CREDENTIALS_FILE`. If we keep that around, it should definitely take precedent before default credentials.

I should also swap (1) and (2) in my above comment. If ever supplied a [google-auth Credentials](https://google-auth.readthedocs.io/en/latest/reference/google.auth.credentials.html#google.auth.credentials.Credentials) object, we should always use that.

**Comment by tswast** [comment] 2018-04-07 00:45
I have fleshed out a design that accounts for this feedback at #161. Closing this issue as a duplicate of that proposal.

**Closed by tswast** 2018-04-07 00:45 UTC
